name: 🚛 Semantic Release

on:
  push:
    branches:
      - main
      - releases/v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 🗃️ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 🏗️ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: 💾 Install Dependencies
        run: |
          npm install @semantic-release/changelog -D &&
          npm install @semantic-release/git -D &&
          npm clean-install

      - name: 🕵️ Verify Attestations and Registry Signatures for Dependencies
        run: npm audit Signatures

      - name: 🏁 Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_SEMANTIC_RELEASE }}
          NPM_TOKEN: ${{ secrets.CI_SEMANTIC_RELEASE }}
        run: npx semantic-release -d
